/**
 * Generates the two client-side syntax grammars (`generated/hvp.tmLanguage.json`
 * for VS Code, `generated/HVP.sublime-syntax` for Sublime Text) from
 * `src/core/keywords.ts`, which is the single source of truth for HVP keyword
 * data. This is what replaces the pre-Phase-2 world where `keywords.ts` (then
 * `hvpKeywords.ts`), `syntaxes/hvp.tmLanguage.json`, and `snippets/hvp.json`
 * had to be hand-kept in sync (see MIGRATION.md).
 *
 * Everything that isn't keyword-list-driven (comments, strings, numbers,
 * operators, the `declaration-name` scope) is a static template below, copied
 * from the pre-Phase-2 hand-written `vscode-hvp/syntaxes/hvp.tmLanguage.json`.
 *
 * Run with `npm run gen-grammars` (compiles then runs `out/tools/gen-grammars.js`).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import {
  BLOCK_CLOSE_KEYWORD,
  BLOCK_OPEN_KEYWORD,
  BUILTIN_FIELDS,
  BUILTIN_METRICS,
  KeywordInfo,
  NON_PAIRED_KEYWORDS,
  PairKind,
  SOURCE_KEYWORDS,
  SOURCE_MASK_WORDS,
  SOURCE_TAGS,
  SOURCE_WILDCARDS,
  TYPE_KEYWORDS,
} from '../src/core/keywords';

// Compiles to out/tools/gen-grammars.js (tsconfig's rootDir is the package
// root, mirroring src/test/tools under out/), so the package root is two
// levels up from __dirname at runtime, not one.
const OUT_DIR = path.resolve(__dirname, '..', '..', 'generated');

// --- keyword-list-driven scope tables -------------------------------------

const GENERATED_HEADER =
  'GENERATED by hvp-language-server/tools/gen-grammars.ts from src/core/keywords.ts — do not edit by hand.';

function names(infos: KeywordInfo[]): string[] {
  return infos.map((info) => info.name);
}

function byName(infos: KeywordInfo[], wanted: string[]): string[] {
  const set = new Set(wanted);
  return infos.filter((info) => set.has(info.name)).map((info) => info.name);
}

/**
 * Trap: within a single alternation, a shorter name that is a strict prefix
 * of a longer dotted name (e.g. `test` vs. `test.percent.pass`) must come
 * *after* the longer one, or the regex engine matches the short prefix first
 * and the rest of the longer name (`.percent.pass`) is left unscoped. Sorting
 * every alternation by string length, descending, before joining sidesteps
 * this regardless of which specific names collide.
 */
function longestFirst(list: string[]): string[] {
  return [...list].sort((a, b) => b.length - a.length);
}

function escapeRegex(name: string): string {
  return name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function alternation(list: string[]): string {
  return `\\b(${group(list)})\\b`;
}

/** The bare `a|b|c` body of an alternation, longest-first, with no `\b`
 * anchors — for tokens like `` `r` `` or `**` whose first and last characters
 * are not word characters, where `\b` would assert the wrong thing. */
function group(list: readonly string[]): string {
  return longestFirst([...list]).map(escapeRegex).join('|');
}

/**
 * The one spelling of `name` in `infos`, or a load-time error.
 *
 * Same reason `keywords.ts`'s `table4Row` throws: a name that quietly fell out
 * of a table would leave the generator emitting a grammar with one scope
 * silently missing, which no output comparison notices. Failing here turns a
 * rename into a build error instead.
 */
function one(infos: readonly KeywordInfo[], name: string): string {
  const found = infos.find((info) => info.name === name);
  if (!found) throw new Error(`gen-grammars: keywords.ts no longer spells '${name}'`);
  return found.name;
}

// keyword.control.hvp: every block open/close keyword, plus the non-paired
// control-flow-ish keywords (subplan, until's elseuntil/else branches).
const BLOCK_KEYWORDS = [
  ...Object.values(BLOCK_OPEN_KEYWORD),
  ...Object.values(BLOCK_CLOSE_KEYWORD),
  ...byName(NON_PAIRED_KEYWORDS, ['subplan', 'elseuntil', 'else']),
];

// Also keyword.control.hvp, kept as a separate alternation (matching the
// hand-written grammar's structure) rather than merged into BLOCK_KEYWORDS.
const FILTER_KEYWORDS = byName(NON_PAIRED_KEYWORDS, ['keep', 'remove', 'where']);

// storage.type.hvp
const DECLARATION_KEYWORDS = byName(NON_PAIRED_KEYWORDS, ['attribute', 'annotation']);

// support.type.hvp
const TYPE_NAMES = names(TYPE_KEYWORDS);

// variable.other.property.hvp: BUILTIN_FIELDS plus the metric-statement
// keywords (goal/aggregator/apply) — the hand-written grammar already
// scoped goal/aggregator here rather than under keywords-block; `apply` is
// new (added to keywords.ts after the hand-written grammar was last
// touched, i.e. exactly the hand-sync drift this generator exists to kill).
const FIELD_NAMES = [...names(BUILTIN_FIELDS), ...byName(NON_PAIRED_KEYWORDS, ['goal', 'aggregator', 'apply'])];

// entity.name.type.hvp
const METRIC_NAMES = names(BUILTIN_METRICS);

// The block openers that are followed by a declared name, for the
// `declaration-name` rule. Which openers take a name is this file's knowledge
// (`metric`/`measure`/`until` don't); *how each one is spelled* still comes
// from the table, so a renamed keyword can't leave a stale literal here.
const NAMED_BLOCK_KEYWORDS = [
  ...(['feature', 'plan', 'override', 'filter'] as PairKind[]).map((kind) => BLOCK_OPEN_KEYWORD[kind]),
  ...byName(NON_PAIRED_KEYWORDS, ['subplan']),
];

// --- source-string scope tables (WS8b) -------------------------------------
//
// Every token below is read out of `keywords.ts` rather than spelled here, for
// the same reason `sourceExpressions.ts` derives its own tag/wildcard tables
// from it: the runtime reader and the highlighter must not be able to disagree
// about which keywords, tags and wildcards exist.

/** `group instance bin` → `group[ \t]+instance[ \t]+bin`. The canonical names
 * are space-normalised; a real source string may space its words differently. */
function keywordWords(name: string): string {
  return name.split(' ').map(escapeRegex).join('[ \\t]+');
}

/** The keywords written `<words>:`, longest-first so `group instance bin` wins
 * over `group instance`, which wins over `group`. */
const SOURCE_PLAIN_KEYWORDS = SOURCE_KEYWORDS.filter((k) => !k.mask).map((k) => k.name);

/** The word the mask-bearing keywords start with (`property`), derived from the
 * table the same way `SOURCE_MASK_WORDS` derives their last word. */
const SOURCE_MASK_HEADS = [...new Set(SOURCE_KEYWORDS.filter((k) => k.mask).map((k) => k.name.split(' ')[0]))];

// Table 4 writes `categoryMask` and the prose under it writes `categorymask`,
// so `sourceExpressions.ts` compares the mask word case-insensitively. Spelled
// out as the two documented casings rather than with an `(?i:...)` group: both
// grammars run on Oniguruma, which supports it, but nothing that can *test* a
// generated pattern does, and an untestable pattern is how the hand-sync drift
// this generator exists to kill gets back in.
const MASK_WORD = `(?:${group([...new Set(SOURCE_MASK_WORDS.flatMap((w) => [w, w.toLowerCase()]))])})`;
const MASK_VALUE = "'[hH][0-9A-Fa-f]*";
const MASK_HEAD = group(SOURCE_MASK_HEADS);

// `:(?!:)` is the `::` rule: the Synopsys database's scope separator is never a
// keyword's colon, so `cmm_pkg::cmm_checker` must not read as a keyword prefix.
const COLON = ':(?!:)';

/**
 * The top-level rule order, shared by both emitters.
 *
 * Order is load-bearing: `#source-statement` must precede `#strings` (a source
 * string is its own little language and the plain string rule would swallow it
 * first), and both must precede `#subplan-parameters` so the `#(` inside
 * `..._cg#(10)::cg...` is never reached. Written once because the two formats
 * spell an include differently but must agree on the sequence — hand-keeping
 * two copies in step is the drift this generator exists to kill.
 */
const INCLUDE_ORDER = [
  'comments',
  'source-statement',
  'strings',
  'numbers',
  'enum-members',
  'aggregate-members',
  'subplan-parameters',
  'declaration-name',
  'keywords-block',
  'keywords-declaration',
  'keywords-type',
  'builtin-metrics',
  'keywords-filter',
  'keywords-field',
  'operators',
];

const PATTERNS = {
  block: alternation(BLOCK_KEYWORDS),
  filter: alternation(FILTER_KEYWORDS),
  declaration: alternation(DECLARATION_KEYWORDS),
  type: alternation(TYPE_NAMES),
  field: alternation(FIELD_NAMES),
  metric: alternation(METRIC_NAMES),
  namedBlock: `(${group(NAMED_BLOCK_KEYWORDS)})`,
  // The two spellings of the `'h###` mask the chapter contradicts itself over,
  // both accepted (as `sourceExpressions.ts` accepts both): the work plan's
  // `property categoryMask 'h00f:` and Table 4's `property: categoryMask 'h00f`.
  sourceMaskBefore: `\\b(${MASK_HEAD})[ \\t]+(${MASK_WORD})[ \\t]*(${MASK_VALUE})[ \\t]*${COLON}`,
  sourceMaskAfter: `\\b(${MASK_HEAD})[ \\t]*${COLON}[ \\t]*(${MASK_WORD})[ \\t]*(${MASK_VALUE})`,
  sourceKeyword: `\\b(${longestFirst(SOURCE_PLAIN_KEYWORDS).map(keywordWords).join('|')})[ \\t]*${COLON}`,
  sourceTag: `(?:${group(SOURCE_TAGS)})`,
  // `**` before `*`, the same longest-first trap one level down.
  sourceWildcard: `(?:${group(SOURCE_WILDCARDS)})`,
  sourceField: `\\b(${escapeRegex(one(BUILTIN_FIELDS, 'source'))})`,
  enumType: `\\b(${escapeRegex(one(TYPE_KEYWORDS, 'enum'))})`,
  aggregateType: `\\b(${escapeRegex(one(TYPE_KEYWORDS, 'aggregate'))})`,
  weightField: `\\b(${escapeRegex(one(BUILTIN_FIELDS, 'weight'))})`,
};

// --- tmLanguage.json (VS Code / TextMate) ----------------------------------

function buildTmLanguage(): object {
  return {
    '//': GENERATED_HEADER,
    $schema: 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
    name: 'HVP',
    scopeName: 'source.hvp',
    fileTypes: ['hvp'],
    patterns: INCLUDE_ORDER.map((name) => ({ include: `#${name}` })),
    repository: {
      comments: {
        patterns: [
          { name: 'comment.line.double-slash.hvp', match: '//.*$' },
          { name: 'comment.block.hvp', begin: '/\\*', end: '\\*/' },
        ],
      },
      strings: {
        name: 'string.quoted.double.hvp',
        begin: '"',
        end: '"',
        patterns: [
          { name: 'constant.character.escape.hvp', match: '\\\\.' },
          { name: 'variable.other.hvp', match: '\\$\\{[A-Za-z_]\\w*\\}' },
        ],
      },
      // WS8b. The `source` statement is scoped as a region rather than by
      // recognising source strings on their own, so that a keywordless
      // pattern (`source = "top.cpu.*"`) still gets its wildcards scoped. It
      // runs to the statement's `;`.
      'source-statement': {
        begin: `${PATTERNS.sourceField}\\s*(=)`,
        beginCaptures: {
          '1': { name: 'variable.other.property.hvp' },
          '2': { name: 'keyword.operator.assignment.hvp' },
        },
        end: ';',
        patterns: [{ include: '#comments' }, { include: '#source-string' }],
      },
      'source-string': {
        name: 'string.quoted.double.hvp',
        patterns: [
          // First, so an escaped `\\*` reads as an escape and not as a wildcard.
          { name: 'constant.character.escape.hvp', match: '\\\\.' },
          // Both mask spellings before the plain keywords: either would also
          // match the bare `property:` branch, and the mask must win.
          {
            match: PATTERNS.sourceMaskBefore,
            captures: {
              '1': { name: 'keyword.other.source.hvp' },
              '2': { name: 'keyword.other.source.hvp' },
              '3': { name: 'constant.numeric.hex.hvp' },
            },
          },
          {
            match: PATTERNS.sourceMaskAfter,
            captures: {
              '1': { name: 'keyword.other.source.hvp' },
              '2': { name: 'keyword.other.source.hvp' },
              '3': { name: 'constant.numeric.hex.hvp' },
            },
          },
          { match: PATTERNS.sourceKeyword, captures: { '1': { name: 'keyword.other.source.hvp' } } },
          { name: 'variable.other.hvp', match: '\\$\\{[A-Za-z_]\\w*\\}' },
          { name: 'keyword.other.tag.hvp', match: PATTERNS.sourceTag },
          { name: 'keyword.operator.wildcard.hvp', match: PATTERNS.sourceWildcard },
        ],
        begin: '"',
        end: '"',
      },
      // WS8b: the members of a declared `enum {...}` attribute/annotation/
      // metric type. `enum-identifier ::= identifier | INT | SNUM`, hence
      // #numbers alongside the identifier rule.
      'enum-members': {
        begin: `${PATTERNS.enumType}\\s*(\\{)`,
        beginCaptures: {
          '1': { name: 'support.type.hvp' },
          '2': { name: 'punctuation.section.braces.begin.hvp' },
        },
        end: '\\}',
        endCaptures: { '0': { name: 'punctuation.section.braces.end.hvp' } },
        patterns: [
          { include: '#comments' },
          { include: '#numbers' },
          { name: 'variable.other.enummember.hvp', match: '[A-Za-z_]\\w*' },
        ],
      },
      // WS8b: `metric aggregate {Line(weight=1.0), Cond(weight=2.0)} Name;`.
      // The members are metric references, so they take the built-in metric
      // scope; `weight` is the built-in annotation of that name.
      'aggregate-members': {
        begin: `${PATTERNS.aggregateType}\\s*(\\{)`,
        beginCaptures: {
          '1': { name: 'support.type.hvp' },
          '2': { name: 'punctuation.section.braces.begin.hvp' },
        },
        end: '\\}',
        endCaptures: { '0': { name: 'punctuation.section.braces.end.hvp' } },
        patterns: [
          { include: '#comments' },
          {
            match: `${PATTERNS.weightField}\\s*(=)`,
            captures: {
              '1': { name: 'variable.other.property.hvp' },
              '2': { name: 'keyword.operator.assignment.hvp' },
            },
          },
          { include: '#numbers' },
          { name: 'entity.name.type.hvp', match: '[A-Za-z_][\\w.]*' },
        ],
      },
      // WS8b: `subplan cache_plan #(root_mod="top.", grpA=0);`. Placed after
      // #strings and #source-statement in the include list, so the `#(` inside
      // a source string (`..._cg#(10)::cg...`) is never reached.
      'subplan-parameters': {
        begin: '(#)(\\()',
        beginCaptures: {
          '1': { name: 'punctuation.definition.parameters.hvp' },
          '2': { name: 'punctuation.section.parens.begin.hvp' },
        },
        end: '\\)',
        endCaptures: { '0': { name: 'punctuation.section.parens.end.hvp' } },
        patterns: [
          { include: '#comments' },
          {
            match: '([A-Za-z_]\\w*)\\s*(=)',
            captures: {
              '1': { name: 'variable.parameter.hvp' },
              '2': { name: 'keyword.operator.assignment.hvp' },
            },
          },
          { include: '#strings' },
          { include: '#numbers' },
        ],
      },
      numbers: {
        patterns: [
          { name: 'constant.numeric.percent.hvp', match: '\\b\\d+(\\.\\d+)?%' },
          { name: 'constant.numeric.float.hvp', match: '\\b\\d+\\.\\d+\\b' },
          { name: 'constant.numeric.integer.hvp', match: '\\b\\d+\\b' },
        ],
      },
      'keywords-block': { name: 'keyword.control.hvp', match: PATTERNS.block },
      'keywords-declaration': { name: 'storage.type.hvp', match: PATTERNS.declaration },
      'keywords-type': { name: 'support.type.hvp', match: PATTERNS.type },
      'keywords-field': { name: 'variable.other.property.hvp', match: PATTERNS.field },
      'builtin-metrics': { name: 'entity.name.type.hvp', match: PATTERNS.metric },
      'keywords-filter': { name: 'keyword.control.hvp', match: PATTERNS.filter },
      operators: {
        patterns: [
          { name: 'keyword.operator.logical.hvp', match: '==|!=|>=|<=|&&|\\|\\||!|>|<' },
          { name: 'keyword.operator.arithmetic.hvp', match: '\\+|-|\\*|/' },
          { name: 'keyword.operator.assignment.hvp', match: '=' },
        ],
      },
      'declaration-name': {
        match: `^\\s*${PATTERNS.namedBlock}\\s+([A-Za-z_]\\w*)`,
        captures: {
          '1': { name: 'keyword.control.hvp' },
          '2': { name: 'entity.name.function.hvp' },
        },
      },
    },
  };
}

// --- HVP.sublime-syntax (Sublime Text) --------------------------------------

function yamlSingleQuoted(pattern: string): string {
  // YAML single-quoted scalars only need '' -> ' escaping. WS8b's `'h###`
  // mask patterns are the first generated regexes that actually contain one.
  return `'${pattern.replace(/'/g, "''")}'`;
}

function buildSublimeSyntax(): string {
  return `%YAML 1.2
---
# ${GENERATED_HEADER}
name: HVP
file_extensions: [hvp]
scope: source.hvp

contexts:
  main:
${INCLUDE_ORDER.map((name) => `    - include: ${name}`).join('\n')}

  comments:
    - match: '//.*$'
      scope: comment.line.double-slash.hvp
    - match: '/\\*'
      scope: punctuation.definition.comment.begin.hvp
      push: block-comment

  block-comment:
    - meta_scope: comment.block.hvp
    - match: '\\*/'
      scope: punctuation.definition.comment.end.hvp
      pop: true

  strings:
    - match: '"'
      scope: punctuation.definition.string.begin.hvp
      push: inside-string

  inside-string:
    - meta_scope: string.quoted.double.hvp
    - match: '\\\\.'
      scope: constant.character.escape.hvp
    - match: '\\$\\{[A-Za-z_]\\w*\\}'
      scope: variable.other.hvp
    - match: '"'
      scope: punctuation.definition.string.end.hvp
      pop: true

  source-statement:
    - match: ${yamlSingleQuoted(`${PATTERNS.sourceField}\\s*(=)`)}
      captures:
        1: variable.other.property.hvp
        2: keyword.operator.assignment.hvp
      push: inside-source-statement

  inside-source-statement:
    - match: ';'
      pop: true
    - include: comments
    - match: '"'
      scope: punctuation.definition.string.begin.hvp
      push: inside-source-string

  inside-source-string:
    - meta_scope: string.quoted.double.hvp
    - match: '\\\\.'
      scope: constant.character.escape.hvp
    - match: ${yamlSingleQuoted(PATTERNS.sourceMaskBefore)}
      captures:
        1: keyword.other.source.hvp
        2: keyword.other.source.hvp
        3: constant.numeric.hex.hvp
    - match: ${yamlSingleQuoted(PATTERNS.sourceMaskAfter)}
      captures:
        1: keyword.other.source.hvp
        2: keyword.other.source.hvp
        3: constant.numeric.hex.hvp
    - match: ${yamlSingleQuoted(PATTERNS.sourceKeyword)}
      captures:
        1: keyword.other.source.hvp
    - match: '\\$\\{[A-Za-z_]\\w*\\}'
      scope: variable.other.hvp
    - match: ${yamlSingleQuoted(PATTERNS.sourceTag)}
      scope: keyword.other.tag.hvp
    - match: ${yamlSingleQuoted(PATTERNS.sourceWildcard)}
      scope: keyword.operator.wildcard.hvp
    - match: '"'
      scope: punctuation.definition.string.end.hvp
      pop: true

  enum-members:
    - match: ${yamlSingleQuoted(`${PATTERNS.enumType}\\s*(\\{)`)}
      captures:
        1: support.type.hvp
        2: punctuation.section.braces.begin.hvp
      push: inside-enum-members

  inside-enum-members:
    - match: '\\}'
      scope: punctuation.section.braces.end.hvp
      pop: true
    - include: comments
    - include: numbers
    - match: '[A-Za-z_]\\w*'
      scope: variable.other.enummember.hvp

  aggregate-members:
    - match: ${yamlSingleQuoted(`${PATTERNS.aggregateType}\\s*(\\{)`)}
      captures:
        1: support.type.hvp
        2: punctuation.section.braces.begin.hvp
      push: inside-aggregate-members

  inside-aggregate-members:
    - match: '\\}'
      scope: punctuation.section.braces.end.hvp
      pop: true
    - include: comments
    - match: ${yamlSingleQuoted(`${PATTERNS.weightField}\\s*(=)`)}
      captures:
        1: variable.other.property.hvp
        2: keyword.operator.assignment.hvp
    - include: numbers
    - match: '[A-Za-z_][\\w.]*'
      scope: entity.name.type.hvp

  subplan-parameters:
    - match: '(#)(\\()'
      captures:
        1: punctuation.definition.parameters.hvp
        2: punctuation.section.parens.begin.hvp
      push: inside-subplan-parameters

  inside-subplan-parameters:
    - match: '\\)'
      scope: punctuation.section.parens.end.hvp
      pop: true
    - include: comments
    - match: '([A-Za-z_]\\w*)\\s*(=)'
      captures:
        1: variable.parameter.hvp
        2: keyword.operator.assignment.hvp
    - include: strings
    - include: numbers

  numbers:
    - match: '\\b\\d+(\\.\\d+)?%'
      scope: constant.numeric.percent.hvp
    - match: '\\b\\d+\\.\\d+\\b'
      scope: constant.numeric.float.hvp
    - match: '\\b\\d+\\b'
      scope: constant.numeric.integer.hvp

  declaration-name:
    - match: ${yamlSingleQuoted(`^\\s*${PATTERNS.namedBlock}\\s+([A-Za-z_]\\w*)`)}
      captures:
        1: keyword.control.hvp
        2: entity.name.function.hvp

  keywords-block:
    - match: ${yamlSingleQuoted(PATTERNS.block)}
      scope: keyword.control.hvp

  keywords-declaration:
    - match: ${yamlSingleQuoted(PATTERNS.declaration)}
      scope: storage.type.hvp

  keywords-type:
    - match: ${yamlSingleQuoted(PATTERNS.type)}
      scope: support.type.hvp

  builtin-metrics:
    - match: ${yamlSingleQuoted(PATTERNS.metric)}
      scope: entity.name.type.hvp

  keywords-filter:
    - match: ${yamlSingleQuoted(PATTERNS.filter)}
      scope: keyword.control.hvp

  keywords-field:
    - match: ${yamlSingleQuoted(PATTERNS.field)}
      scope: variable.other.property.hvp

  operators:
    - match: '==|!=|>=|<=|&&|\\|\\||!|>|<'
      scope: keyword.operator.logical.hvp
    - match: '\\+|-|\\*|/'
      scope: keyword.operator.arithmetic.hvp
    - match: '='
      scope: keyword.operator.assignment.hvp
`;
}

export function generateGrammars(): { tmLanguage: object; sublimeSyntax: string } {
  return { tmLanguage: buildTmLanguage(), sublimeSyntax: buildSublimeSyntax() };
}

function main(): void {
  const { tmLanguage, sublimeSyntax } = generateGrammars();
  // generated/ is gitignored (fully derived — see .gitignore), so it may not
  // exist yet on a fresh checkout.
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(path.join(OUT_DIR, 'hvp.tmLanguage.json'), JSON.stringify(tmLanguage, null, 2) + '\n');
  writeFileSync(path.join(OUT_DIR, 'HVP.sublime-syntax'), sublimeSyntax);
  // eslint-disable-next-line no-console
  console.log(`Wrote ${OUT_DIR}/hvp.tmLanguage.json and ${OUT_DIR}/HVP.sublime-syntax`);
}

if (require.main === module) {
  main();
}
