/**
 * Generates the two client-side syntax grammars (`generated/hvp.tmLanguage.json`
 * for VS Code, `generated/HVP.sublime-syntax` for Sublime Text) from
 * `src/core/keywords.ts`, which is the single source of truth for HVP keyword
 * data. This is what replaces the pre-Phase-2 world where `keywords.ts` (then
 * `hvpKeywords.ts`), `syntaxes/hvp.tmLanguage.json`, and `snippets/hvp.json`
 * had to be hand-kept in sync (see MIGRATION.md).
 *
 * Everything that isn't keyword-list-driven (comments, strings, numbers,
 * operators, the `declaration-name` scope) is a static template below, copied
 * from the pre-Phase-2 hand-written `vscode-hvp/syntaxes/hvp.tmLanguage.json`.
 *
 * Run with `npm run gen-grammars` (compiles then runs `out/tools/gen-grammars.js`).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import {
  BLOCK_CLOSE_KEYWORD,
  BLOCK_OPEN_KEYWORD,
  BUILTIN_FIELDS,
  BUILTIN_METRICS,
  KeywordInfo,
  NON_PAIRED_KEYWORDS,
  TYPE_KEYWORDS,
} from '../src/core/keywords';

// Compiles to out/tools/gen-grammars.js (tsconfig's rootDir is the package
// root, mirroring src/test/tools under out/), so the package root is two
// levels up from __dirname at runtime, not one.
const OUT_DIR = path.resolve(__dirname, '..', '..', 'generated');

// --- keyword-list-driven scope tables -------------------------------------

const GENERATED_HEADER =
  'GENERATED by hvp-language-server/tools/gen-grammars.ts from src/core/keywords.ts — do not edit by hand.';

function names(infos: KeywordInfo[]): string[] {
  return infos.map((info) => info.name);
}

function byName(infos: KeywordInfo[], wanted: string[]): string[] {
  const set = new Set(wanted);
  return infos.filter((info) => set.has(info.name)).map((info) => info.name);
}

/**
 * Trap: within a single alternation, a shorter name that is a strict prefix
 * of a longer dotted name (e.g. `test` vs. `test.percent.pass`) must come
 * *after* the longer one, or the regex engine matches the short prefix first
 * and the rest of the longer name (`.percent.pass`) is left unscoped. Sorting
 * every alternation by string length, descending, before joining sidesteps
 * this regardless of which specific names collide.
 */
function longestFirst(list: string[]): string[] {
  return [...list].sort((a, b) => b.length - a.length);
}

function escapeRegex(name: string): string {
  return name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function alternation(list: string[]): string {
  return `\\b(${longestFirst(list)
    .map(escapeRegex)
    .join('|')})\\b`;
}

// keyword.control.hvp: every block open/close keyword, plus the non-paired
// control-flow-ish keywords (subplan, until's elseuntil/else branches).
const BLOCK_KEYWORDS = [
  ...Object.values(BLOCK_OPEN_KEYWORD),
  ...Object.values(BLOCK_CLOSE_KEYWORD),
  ...byName(NON_PAIRED_KEYWORDS, ['subplan', 'elseuntil', 'else']),
];

// Also keyword.control.hvp, kept as a separate alternation (matching the
// hand-written grammar's structure) rather than merged into BLOCK_KEYWORDS.
const FILTER_KEYWORDS = byName(NON_PAIRED_KEYWORDS, ['keep', 'remove', 'where']);

// storage.type.hvp
const DECLARATION_KEYWORDS = byName(NON_PAIRED_KEYWORDS, ['attribute', 'annotation']);

// support.type.hvp
const TYPE_NAMES = names(TYPE_KEYWORDS);

// variable.other.property.hvp: BUILTIN_FIELDS plus the metric-statement
// keywords (goal/aggregator/apply) — the hand-written grammar already
// scoped goal/aggregator here rather than under keywords-block; `apply` is
// new (added to keywords.ts after the hand-written grammar was last
// touched, i.e. exactly the hand-sync drift this generator exists to kill).
const FIELD_NAMES = [...names(BUILTIN_FIELDS), ...byName(NON_PAIRED_KEYWORDS, ['goal', 'aggregator', 'apply'])];

// entity.name.type.hvp
const METRIC_NAMES = names(BUILTIN_METRICS);

const PATTERNS = {
  block: alternation(BLOCK_KEYWORDS),
  filter: alternation(FILTER_KEYWORDS),
  declaration: alternation(DECLARATION_KEYWORDS),
  type: alternation(TYPE_NAMES),
  field: alternation(FIELD_NAMES),
  metric: alternation(METRIC_NAMES),
};

// --- tmLanguage.json (VS Code / TextMate) ----------------------------------

function buildTmLanguage(): object {
  return {
    '//': GENERATED_HEADER,
    $schema: 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
    name: 'HVP',
    scopeName: 'source.hvp',
    fileTypes: ['hvp'],
    patterns: [
      { include: '#comments' },
      { include: '#strings' },
      { include: '#numbers' },
      { include: '#declaration-name' },
      { include: '#keywords-block' },
      { include: '#keywords-declaration' },
      { include: '#keywords-type' },
      { include: '#builtin-metrics' },
      { include: '#keywords-filter' },
      { include: '#keywords-field' },
      { include: '#operators' },
    ],
    repository: {
      comments: {
        patterns: [
          { name: 'comment.line.double-slash.hvp', match: '//.*$' },
          { name: 'comment.block.hvp', begin: '/\\*', end: '\\*/' },
        ],
      },
      strings: {
        name: 'string.quoted.double.hvp',
        begin: '"',
        end: '"',
        patterns: [
          { name: 'constant.character.escape.hvp', match: '\\\\.' },
          { name: 'variable.other.hvp', match: '\\$\\{[A-Za-z_]\\w*\\}' },
        ],
      },
      numbers: {
        patterns: [
          { name: 'constant.numeric.percent.hvp', match: '\\b\\d+(\\.\\d+)?%' },
          { name: 'constant.numeric.float.hvp', match: '\\b\\d+\\.\\d+\\b' },
          { name: 'constant.numeric.integer.hvp', match: '\\b\\d+\\b' },
        ],
      },
      'keywords-block': { name: 'keyword.control.hvp', match: PATTERNS.block },
      'keywords-declaration': { name: 'storage.type.hvp', match: PATTERNS.declaration },
      'keywords-type': { name: 'support.type.hvp', match: PATTERNS.type },
      'keywords-field': { name: 'variable.other.property.hvp', match: PATTERNS.field },
      'builtin-metrics': { name: 'entity.name.type.hvp', match: PATTERNS.metric },
      'keywords-filter': { name: 'keyword.control.hvp', match: PATTERNS.filter },
      operators: {
        patterns: [
          { name: 'keyword.operator.logical.hvp', match: '==|!=|>=|<=|&&|\\|\\||!|>|<' },
          { name: 'keyword.operator.arithmetic.hvp', match: '\\+|-|\\*|/' },
          { name: 'keyword.operator.assignment.hvp', match: '=' },
        ],
      },
      'declaration-name': {
        match: '^\\s*(feature|plan|subplan|override|filter)\\s+([A-Za-z_]\\w*)',
        captures: {
          '1': { name: 'keyword.control.hvp' },
          '2': { name: 'entity.name.function.hvp' },
        },
      },
    },
  };
}

// --- HVP.sublime-syntax (Sublime Text) --------------------------------------

function yamlSingleQuoted(pattern: string): string {
  // YAML single-quoted scalars only need '' -> ' escaping; none of our
  // generated regexes contain a literal single quote, but handle it anyway.
  return `'${pattern.replace(/'/g, "''")}'`;
}

function buildSublimeSyntax(): string {
  return `%YAML 1.2
---
# ${GENERATED_HEADER}
name: HVP
file_extensions: [hvp]
scope: source.hvp

contexts:
  main:
    - include: comments
    - include: strings
    - include: numbers
    - include: declaration-name
    - include: keywords-block
    - include: keywords-declaration
    - include: keywords-type
    - include: builtin-metrics
    - include: keywords-filter
    - include: keywords-field
    - include: operators

  comments:
    - match: '//.*$'
      scope: comment.line.double-slash.hvp
    - match: '/\\*'
      scope: punctuation.definition.comment.begin.hvp
      push: block-comment

  block-comment:
    - meta_scope: comment.block.hvp
    - match: '\\*/'
      scope: punctuation.definition.comment.end.hvp
      pop: true

  strings:
    - match: '"'
      scope: punctuation.definition.string.begin.hvp
      push: inside-string

  inside-string:
    - meta_scope: string.quoted.double.hvp
    - match: '\\\\.'
      scope: constant.character.escape.hvp
    - match: '\\$\\{[A-Za-z_]\\w*\\}'
      scope: variable.other.hvp
    - match: '"'
      scope: punctuation.definition.string.end.hvp
      pop: true

  numbers:
    - match: '\\b\\d+(\\.\\d+)?%'
      scope: constant.numeric.percent.hvp
    - match: '\\b\\d+\\.\\d+\\b'
      scope: constant.numeric.float.hvp
    - match: '\\b\\d+\\b'
      scope: constant.numeric.integer.hvp

  declaration-name:
    - match: '^\\s*(feature|plan|subplan|override|filter)\\s+([A-Za-z_]\\w*)'
      captures:
        1: keyword.control.hvp
        2: entity.name.function.hvp

  keywords-block:
    - match: ${yamlSingleQuoted(PATTERNS.block)}
      scope: keyword.control.hvp

  keywords-declaration:
    - match: ${yamlSingleQuoted(PATTERNS.declaration)}
      scope: storage.type.hvp

  keywords-type:
    - match: ${yamlSingleQuoted(PATTERNS.type)}
      scope: support.type.hvp

  builtin-metrics:
    - match: ${yamlSingleQuoted(PATTERNS.metric)}
      scope: entity.name.type.hvp

  keywords-filter:
    - match: ${yamlSingleQuoted(PATTERNS.filter)}
      scope: keyword.control.hvp

  keywords-field:
    - match: ${yamlSingleQuoted(PATTERNS.field)}
      scope: variable.other.property.hvp

  operators:
    - match: '==|!=|>=|<=|&&|\\|\\||!|>|<'
      scope: keyword.operator.logical.hvp
    - match: '\\+|-|\\*|/'
      scope: keyword.operator.arithmetic.hvp
    - match: '='
      scope: keyword.operator.assignment.hvp
`;
}

export function generateGrammars(): { tmLanguage: object; sublimeSyntax: string } {
  return { tmLanguage: buildTmLanguage(), sublimeSyntax: buildSublimeSyntax() };
}

function main(): void {
  const { tmLanguage, sublimeSyntax } = generateGrammars();
  // generated/ is gitignored (fully derived — see .gitignore), so it may not
  // exist yet on a fresh checkout.
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(path.join(OUT_DIR, 'hvp.tmLanguage.json'), JSON.stringify(tmLanguage, null, 2) + '\n');
  writeFileSync(path.join(OUT_DIR, 'HVP.sublime-syntax'), sublimeSyntax);
  // eslint-disable-next-line no-console
  console.log(`Wrote ${OUT_DIR}/hvp.tmLanguage.json and ${OUT_DIR}/HVP.sublime-syntax`);
}

if (require.main === module) {
  main();
}
